import { ChildProps } from '@/types'
import type { Metadata } from 'next'
import { JetBrains_Mono, Roboto } from 'next/font/google'
import './globals.css'

const jetB = JetBrains_Mono({
	weight: '400',
	subsets: ['latin'],
	variable: '--font-jetbrains-mono',
})
const roboto = Roboto({
	weight: '700',
	subsets: ['latin'],
	variable: '--font-roboto-mono',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: ChildProps) {
	return (
		<html lang='en'>
			<body className={`${roboto.variable} ${jetB.variable} antialiased dark`}>
				{children}
			</body>
		</html>
	)
}
